import { useEffect } from "react";
import Head from 'next/head'
import { ContentImageCatForCheck } from "../components/ContentImageCatForCheck";

export default function imageCatForCheck() {

  return (
    <>
      <Head>
        <title>ImageCatForCheck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='imageCatForCheck'>
        <ContentImageCatForCheck />
      </main>
    </>
  )
}
