import { useEffect } from "react";
import Head from 'next/head'
import { ContentSchema } from "../components/ContentSchema";

export default function Schema() {

  return (
    <>
      <Head>
        <title>Schema</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='schema'>
        <ContentSchema />
      </main>
    </>
  )
}
